apiVersion: v1
kind: Deployment
metadata:
  name: static-nginx
  labels:
    name: static-nginx
    app: static-nginx
    env: dev
    team: riker
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: /usr/share/nginx/html/index.html
        name: nginx-conf
        subPath: index.html
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-index-html-configmap
  data:
    nginx-index.html-configmap: |
      <html><H1>Hello World!</H1></html>
#  immutable: true
